### ISSUE TITLE
Compile fails after usual renaming with 

### ISSUE THREAD

**Issue by Ntemis** [FluBBaOfWard/K80DS#1]
Cart.s
/home/demetris/Desktop/Development/IronHorseDS/source/Cart.s: Assembler messages:
/home/demetris/Desktop/Development/IronHorseDS/source/Cart.s:33: Error: file not found: ironhors/13c_h03.bin
/home/demetris/Desktop/Development/IronHorseDS/source/Cart.s:34: Error: file not found: ironhors/12c_h02.bin
/home/demetris/Desktop/Development/IronHorseDS/source/Cart.s:36: Error: file not found: ironhors/10c_h01.bin
/home/demetris/Desktop/Development/IronHorseDS/source/Cart.s:38: Error: file not found: ironhors/08f_h06.bin
/home/demetris/Desktop/Development/IronHorseDS/source/Cart.s:39: Error: file not found: ironhors/09f_h07.bin
/home/demetris/Desktop/Development/IronHorseDS/source/Cart.s:40: Error: file not found: ironhors/07f_h05.bin
/home/demetris/Desktop/Development/IronHorseDS/source/Cart.s:41: Error: file not found: ironhors/06f_h04.bin
/home/demetris/Desktop/Development/IronHorseDS/source/Cart.s:43: Error: file not found: ironhors/03f_h08.bin
/home/demetris/Desktop/Development/IronHorseDS/source/Cart.s:44: Error: file not found: ironhors/04f_h09.bin
/home/demetris/Desktop/Development/IronHorseDS/source/Cart.s:45: Error: file not found: ironhors/05f_h10.bin
/home/demetris/Desktop/Development/IronHorseDS/source/Cart.s:46: Error: file not found: ironhors/10f_h12.bin
/home/demetris/Desktop/Development/IronHorseDS/source/Cart.s:47: Error: file not found: ironhors/10f_h11.bin
make[1]: *** [/opt/devkitpro/devkitARM/base_rules:95: Cart.o] Error 1
make: *** [Makefile:121: build] Error 2

**Comment by FluBBaOfWard** [comment]
Pushed new source.

**Comment by Ntemis** [comment]
grit /home/demetris/Desktop/Development/IronHorseDS/source/Shared/graphics/EmuFont.png -fts -oEmuFont
EmuFont.s
Main.c
EmuMenu.c
/home/demetris/Desktop/Development/IronHorseDS/source/Shared/EmuMenu.c: In function 'flickSet':
/home/demetris/Desktop/Development/IronHorseDS/source/Shared/EmuMenu.c:793:9: error: 'g_flicker' undeclared (first use in this function); did you mean 'gFlicker'?
  793 |         g_flicker++;
      |         ^~~~~~~~~
      |         gFlicker
/home/demetris/Desktop/Development/IronHorseDS/source/Shared/EmuMenu.c:793:9: note: each undeclared identifier is reported only once for each function it appears in
/home/demetris/Desktop/Development/IronHorseDS/source/Shared/EmuMenu.c:796:17: error: 'g_twitch' undeclared (first use in this function); did you mean 'gTwitch'?
  796 |                 g_twitch = 0;
      |                 ^~~~~~~~
      |                 gTwitch
make[1]: *** [/opt/devkitpro/devkitARM/base_rules:85: EmuMenu.o] Error 1
make: *** [Makefile:121: build] Error 2

**Comment by FluBBaOfWard** [comment]
You need to get your git-client to also update submodules  to the specified revision.

**Comment by Ntemis** [comment]
/home/demetris/Desktop/Development/DoubleDribbleDS/source/Cart.s:3:10: fatal error: equates.h: No such file or directory
    3 | #include "equates.h"
Equates.h is the fix
Edit : Wrong repo with this issue
